### ISSUE TITLE
ImportError: No module named libhector_vision_algorithms_py

### ISSUE THREAD

**Issue by LGK199408** [tu-darmstadt-ros-pkg/hector_vision#3]
roslaunch hector_fast_hazmat_detection hazmat_detection.launch
... logging to /home/lgk/.ros/log/040e0d2a-4b17-11e9-b134-70c94e4b3b5a/roslaunch-lgk-VivoBook-15-ASUS-Laptop-X542UF-22660.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://lgk-VivoBook-15-ASUS-Laptop-X542UF:34323/

SUMMARY
========

PARAMETERS
 * /hazmat_detection/detection_frequency: 1.0
 * /hazmat_detection/image_projection_raycast: False
 * /hazmat_detection/min_match_count: 5
 * /hazmat_detection/model_folder: /home/lgk/catkin_...
 * /hazmat_detection/periodic_detection: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    hazmat_detection (hector_fast_hazmat_detection/hazmat_detection_node.py)

auto-starting new master
process[master]: started with pid [22670]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 040e0d2a-4b17-11e9-b134-70c94e4b3b5a
process[rosout-1]: started with pid [22683]
started core service [/rosout]
process[hazmat_detection-2]: started with pid [22695]
Traceback (most recent call last):
  File "/home/lgk/catkin_ws/src/hector_vision/hector_fast_hazmat_detection/src/hazmat_detection_node.py", line 19, in <module>
    import hazmat_detection
  File "/home/lgk/catkin_ws/src/hector_vision/hector_fast_hazmat_detection/src/hazmat_detection.py", line 5, in <module>
    import hector_vision
  File "/usr/local/lib/python2.7/dist-packages/hector_vision/__init__.py", line 1, in <module>
    from libhector_vision_algorithms_py import *
ImportError: No module named libhector_vision_algorithms_py
[hazmat_detection-2] process has died [pid 22695, exit code 1, cmd /home/lgk/catkin_ws/src/hector_vision/hector_fast_hazmat_detection/src/hazmat_detection_node.py ~image:=arm_rgbd_cam/rgb/image_raw image_percept:=/detection/visual_detection ~enabled:=/startup_check/enabled ~enabled_status:=/startup_check/hazmat_detection/enabled_status __name:=hazmat_detection __log:=/home/lgk/.ros/log/040e0d2a-4b17-11e9-b134-70c94e4b3b5a/hazmat_detection-2.log].
log file: /home/lgk/.ros/log/040e0d2a-4b17-11e9-b134-70c94e4b3b5a/hazmat_detection-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
^Cshutting down processing monitor...
... shutting down processing monitor complete
done

How can I fix it?

**Comment by StefanFabian** [comment]
Did you build the other hector_vision packages, namely, hector_vision_algorithms and hector_vision_algorithms_py, and resource the .bashrc or open a clean terminal?

Mind if I ask, what you're trying to achieve? The code for this hasn't been touched since the last time it was used and had to be adapted quick and dirty to work with the worst case for this approach, hence, it would require quite some work to make it more general and reliable.
I would classify its current state as highly experimental.

**Comment by LGK199408** [comment]
I want to do some detection on hazmat and I have built the project (hector_vision_algorithms) and (hector_vision_algorithms_py), but I haven't resource the .bashrc.  

and I git it in my ~/catkin_ws/src   and "catkin make" in /catkin_ws 
and I roslaunch hector_fast_hazmat_detection hazmat_detection.launch.
The terminal show "ImportError: No module named hector_vision"

so I "sudo python setup.py install" in the project (hector_vision_algorithms_py)
and I roslaunch hector_fast_hazmat_detection hazmat_detection.launch.  again
The terminal show "ImportError: No module named libhector_vision_algorithms_py"

it seems like the module.cpp(hector_vision_algorithms_py) doesn't work.

**Comment by LGK199408** [comment]
lgk@lgk-VivoBook-15-ASUS-Laptop-X542UF:~/catkin_ws$ catkin_make
Base path: /home/lgk/catkin_ws
Source space: /home/lgk/catkin_ws/src
Build space: /home/lgk/catkin_ws/build
Devel space: /home/lgk/catkin_ws/devel
Install space: /home/lgk/catkin_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/lgk/catkin_ws/build"
####
####
#### Running command: "make -j8 -l8" in "/home/lgk/catkin_ws/build"
####
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Building CXX object hector_vision/hector_vision_algorithms_py/CMakeFiles/hector_vision_algorithms_py.dir/src/module.cpp.o
[  1%] Built target hector_vision_algorithms
[  1%] Built target std_msgs_generate_messages_eus
[  1%] Built target std_msgs_generate_messages_cpp
[  1%] Built target geometry_msgs_generate_messages_cpp
[  1%] Built target geometry_msgs_generate_messages_eus
[  1%] Building CXX object hector_vision/hector_vision_algorithms_py/CMakeFiles/hector_vision_algorithms_py.dir/np_opencv_converter/np_opencv_converter.cpp.o
[  1%] Built target _hector_elevation_msgs_generate_messages_check_deps_ElevationGrid
[  2%] Building CXX object hector_vision/hector_vision_algorithms_py/CMakeFiles/hector_vision_algorithms_py.dir/np_opencv_converter/utils/conversion.cpp.o
......
......
......
 98%] Linking CXX executable /home/lgk/catkin_ws/devel/lib/hector_object_tracker/object_tracker
[ 98%] Linking CXX executable /home/lgk/catkin_ws/devel/lib/hector_exploration_node/exploration_planner_node
[ 98%] Built target exploration_planner_node
[ 98%] Built target object_tracker
[100%] Linking CXX executable /home/lgk/catkin_ws/devel/lib/hector_mapping/hector_mapping
[100%] Built target hector_mapping
sour[100%] Built target hector_color_detection_nodelet
lgk@lgk-VivoBook-15-ASUS-Laptop-X542UF:~/catkin_ws$ source devel/setup.bash 
lgk@lgk-VivoBook-15-ASUS-Laptop-X542UF:~/catkin_ws$ 
lgk@lgk-VivoBook-15-ASUS-Laptop-X542UF:~/catkin_ws$ 
lgk@lgk-VivoBook-15-ASUS-Laptop-X542UF:~/catkin_ws$ roslaunch hector_fast_hazmat_detection hazmat_detection.launch 
... logging to /home/lgk/.ros/log/6530171c-4b83-11e9-b773-70c94e4b3b5a/roslaunch-lgk-VivoBook-15-ASUS-Laptop-X542UF-11020.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://lgk-VivoBook-15-ASUS-Laptop-X542UF:35349/

SUMMARY
========

PARAMETERS
 * /hazmat_detection/detection_frequency: 1.0
 * /hazmat_detection/image_projection_raycast: False
 * /hazmat_detection/min_match_count: 5
 * /hazmat_detection/model_folder: /home/lgk/catkin_...
 * /hazmat_detection/periodic_detection: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    hazmat_detection (hector_fast_hazmat_detection/hazmat_detection_node.py)

auto-starting new master
process[master]: started with pid [11030]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 6530171c-4b83-11e9-b773-70c94e4b3b5a
process[rosout-1]: started with pid [11043]
started core service [/rosout]
process[hazmat_detection-2]: started with pid [11056]
Traceback (most recent call last):
  File "/home/lgk/catkin_ws/src/hector_vision/hector_fast_hazmat_detection/src/hazmat_detection_node.py", line 19, in <module>
    import hazmat_detection
  File "/home/lgk/catkin_ws/src/hector_vision/hector_fast_hazmat_detection/src/hazmat_detection.py", line 5, in <module>
    import hector_vision
ImportError: No module named hector_vision

**Comment by LGK199408** [comment]
I have changed the CMakeLists.txt in project(hector_vision_algorithms_py) 
cmake_minimum_required(VERSION 2.8.3)
project(hector_vision_algorithms_py)


if use add_python_export_library if can't catkin make .  

so How to fix it?
find_package(catkin_simple REQUIRED COMPONENTS hector_vision_algorithms)

catkin_simple()

# Set up the python exports.
SET(PY_PROJECT_NAME ${PROJECT_NAME})
SET(PY_PACKAGE_DIR python/hector_vision)

add_library(${PY_PROJECT_NAME} ${PY_PACKAGE_DIR}
                          src/module.cpp np_opencv_converter/np_opencv_converter.cpp np_opencv_converter/utils/conversion.cpp
                          )

cs_install()
cs_export()

**Comment by LGK199408** [comment]
Unknown CMake command "add_python_export_library".

**Comment by StefanFabian** [comment]
Wait, so you've changed the CMakeLists.txt because you had a build error?
That should've been your first comment since I'm pretty sure the change you did there caused the problem you're having. `add_library` and `add_python_export_library` are completely different statements. One is for creating a target library that may be used and linked against by other C++ libraries/executables whereas the latter is a convenience function that also makes sure that the library and python bindings can be found and used from python.
No wonder it can't find the package if you simply replace that line.
Are you maybe missing the **python_module** package which is part of ETHZ's [Schweizer Messer](https://github.com/ethz-asl/schweizer_messer)?
Adding that to your workspace should fix the missing `add_python_export_library` error.

PS: Please use code blocks when you paste in file contents or console outputs because it gets unreadable if you don't.

**Comment by LGK199408** [comment]
Thanks a lot!!!
